One Too Many
============

All of the applications and utilities of this repository
consists of just a single file.

This readme is (supposedly) the one too many (and that's good).

Each of these files includes their own License/Copyright information.


for users
---------


==== link:zz.pl[zz]

Full-terminal interactive chdir utility; navigate through directories
using arrow keys and filtering text. Simple four-liner is to be added
to shell rc files for this to be effective (listed in the beginning of
the file, just after BSD-2-Clause SPDX license idenfifier line).


==== link:sshlessfs[sshlessfs]

Mount filesystem from remote system like sshfs but data connection for
transferring filesystem content between hosts is unencrypted.

In addition to "normal" mount also "reverse" mount is avaible; i.e. local
filesystem is mounted to remote host.

Sshlessfs uses ssh to create connection between hosts and when that is
created it launches sshfs(1) to the host where filesystem is to be
mounted and sftp-server(8) to the host which provides the filesystem.


middle ground
-------------


==== link:nowsync.pl[nowsync.pl]

Synchronize local directory tree to one or more remote directories and keeps
updating further changes to remotes.

Linux inotify(7) is used to recognize changes in the local file system

Simplest usage command line is +nowsync.pl . remotehost:remotedir+
which copies local current directory (tree) to 'remotedir' at 'remotehost'.


==== link:dhcphaxd.pl[dhcphaxd.pl]

Offer fixed IP address to any DHCP client making a request. Very useful for
e.g. to bootstrap initial device connections or doing development through
"point-to-point" ethernet cable between 2 computers.

Uses tcpdump(8) to bypass firewall for reading DHCP traffic.


==== link:sfv[sfv]

Manage versions of a file in a +{filename},sfv+ file. The file format for
+,sfv+ file is 'ar(5)' and the original file is never modified by this tool.


==== link:ipv6llchat.pl[ipv6llchat.pl] (prototype)

Send short messages to the people near you on their computers connected
to the same local area network. These computers does not need to have
any other than (required) ipv6 link local address configured (i.e.
communication is possible even when getting ip address fails for some reason).


developer tools
---------------


==== link:uni2htmldiff.py[uni2htmldiff.py]

Create side-by-side html 5 document from unified diff source.

Example run
....
   $ git show 5d00a0440 | ./uni2htmldiff.py -o difftest.html 88 -
   $ echo file://$PWD/difftest.html
....
and give the resulting file:// url to web browser for further inspection.

~Note to self: check out ssdiff~


==== link:lossybindiff.py[lossybindiff.py]

Print side-by-side (lossy) hex-ascii dump of 2 files, 2 "lines" (32 bytes)
of context. If in-context difference is large, shows (only) 4 "lines"
(64 bytes) of differing data from beginning and end of context.

This is early release; more testing, and program options to be added;
Neverthelss seems to work at least a bit...


==== link:c-oneliner.sh[c-oneliner.sh]

"One line" of C code given from command line compiled in +main()+ and
then executed (by default). Useful for quickly testing simple things.


server setups
-------------


==== link:gitrepos.sh[gitrepos.sh]

Share git repositories (and files) among friendly and polite users.

This provides somewhat more features than git-shell(1) but less than
e.g. gitolite (git-wise).

For filesystem access one(tm), in addition to simple scp, can activate
sftp-server (for sftp/sshfs!) feature (by removing some comments)...

Not much effort has been done to ensure safety from malicious intent,
but some protection against accidental damage from friendly and polite
people has been implemented.
